version: '3.4'

services:
  tesapi:
    image: ${DOCKER_REGISTRY-}tesapi
    build:
      context: .
      dockerfile: TesAPI/Dockerfile

  sqlserver:
        image: microsoft/mssql-server-linux
        restart: always
        ports:
            - 1833:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
      


